fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
#    openssl: "https://github.com/camptocamp/puppet-openssl"
#    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
#    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
#    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
#    dism: "https://github.com/puppetlabs/puppetlabs-dism.git"
#    httpauth: "https://github.com/jamtur01/puppet-httpauth"
#    htpasswd: "https://github.com/leinaddm/puppet-htpasswd.git"
  symlinks:
    atomia: "#{source_dir}"
